MoneyHash/js-sdk

.env.production, .env.staging, index.html, package.json, src/headlessMoneyHash.ts, src/playground.ts, src/sdkApiHandler.ts, src/sdkEmbed.ts, src/types/events.ts, src/types/headless.ts, src/types/intent.ts, src/types/styles.ts, src/utils/getIframeUrl.ts, src/utils/isEmpty.ts, src/utils/loadScript.ts, src/vite-env.d.ts, vite.config.ts, yarn.lock
=> feat: Apple pay native sdk integration

package.json, src/headlessMoneyHash.ts, src/types/headless.ts, src/utils/getApiUrl.ts
=> feat(getIntentMethods): add required billing fields for each method

.env.development, src/headlessMoneyHash.ts
https://www.loom.com/share/901a3340e05248f6b91b441b276e2bbb?sid=541aa61a-cae8-406b-b00b-368a74afece2
checkout PR - https://github.com/MoneyHash/one/pull/4502
=> chore: remove provider_id from native submit

src/types/headless.ts
Recommended methods type for failed routing transaction
=> feat: recommended methods for transaction failed for routing

package.json, src/headlessMoneyHash.ts, src/utils/getMissingCardElement.ts
https://github.com/user-attachments/assets/b82d936c-acbf-4502-b321-66e7aad14382
=> fix: throw error when card element is not created

.env.development, src/utils/getMissingCardElement.ts
https://www.loom.com/share/365cde4b06804c6490e96baca2dcf90e?sid=93417936-ba17-43ad-b18b-6afd109414fe
=> feat: make card holder name optional

src/headlessMoneyHash.ts, src/types/intent.ts
https://www.loom.com/share/cdc95dbdc5b04035b5d04c2954981d55?sid=a52169f5-f352-4df3-b57d-c3de42e31ff8
=> [ENG-4774] feat: add updateIntentMetadata method in the sdk

src/types/standaloneFields.ts
=> [ENG-4819]: feat: add brand name to cardNumberChange event payload

src/headlessMoneyHash.ts, src/types/standaloneFields.ts
https://jam.dev/c/cd8ebceb-93a1-4ed6-9942-bebbd4bfabae
=> feat(standalone fields): customize font size and padding for inputs

src/types/standaloneFields.ts
=> [ENG-4819]: unknown card string

src/headlessMoneyHash.ts, src/types/standaloneFields.ts
https://jam.dev/c/6d6221f0-907d-408f-b33c-b02419865ac0
=> feat(standalone fields): runtime error for card fields

src/headlessMoneyHash.ts, src/types/standaloneFields.ts
=> fix(standalone fields): on error callback event type

src/headlessMoneyHash.ts
https://jam.dev/c/973e5ea9-4dac-4a51-827b-13b592eebb8e
=> feat(standalone fields): save card forms functionality

src/types/headless.ts
=> [ENG-4833] feat: add first 6 digits to saved card

src/headlessMoneyHash.ts, src/types/standaloneFields.ts
https://jam.dev/c/80eafcc3-c04d-4c38-9926-c00ce4a66507
=> feat(standalone fields): listener to form fields validity change

src/headlessMoneyHash.ts, src/types/standaloneFields.ts
https://jam.dev/c/64253a4e-aed9-4b7a-8746-6f037bac7523
=> feat(standalone fields): dynamic color property based on state

src/headlessMoneyHash.ts, src/types/headless.ts, src/utils/waitForSeconds.ts
https://www.loom.com/share/d812ab8d712545fa9f702d6e0e10a3cb?sid=7b5add1e-cabb-4f8f-bd60-ad6c8ceb6e7f
https://jam.dev/c/f30e52c4-9baa-4973-ba30-4a2eb4e87a71
=> fix: redirect to result page inside iframe or popup window

package.json, src/headlessMoneyHash.ts
https://jam.dev/c/845660b7-3dc9-4529-870b-b7b96969c45f
```ts
const { expirationDate } = intentDetails.intent;
moneyHash.onExpiration(expirationDate, () => {
console.log('intent expired!');
});
```
=> feat: expiration event listener

src/headlessMoneyHash.ts, src/standaloneFields/utils/DeferredPromise.ts, src/types/headless.ts, src/types/standaloneFields.ts
https://jam.dev/c/01ab9170-23ef-4b62-b3ae-825b48dcdbda
=> feat: get payment methods using public api key

src/headlessMoneyHash.ts
https://jam.dev/c/3ebc24c9-b2ee-4261-9679-0829fad05388
=> fix: embed result and confirmation in case of redirection

src/headlessMoneyHash.ts, src/moneyHash.ts, src/sdkEmbed.ts
https://jam.dev/c/e49974ff-45b2-4ef1-a3c5-7a3abebe9ece
=> feat: rendered moneyhash checkout iframe height detection

package.json, src/headlessMoneyHash.ts, src/moneyHash.ts
https://jam.dev/c/11804cab-1be3-4d78-aec7-48afedc03333
=> fix: native google pay for not live intents

src/headlessMoneyHash.ts, src/moneyHash.ts, src/sdkEmbed.ts, src/types/headless.ts
Allow user to pass `sandbox` attribute to enable bypass the browser constraints for top navigation and cross origin
=> [ENG-5368]: feat: allow user of renderForm to add iframe sandbox attribute

src/sdkEmbed.ts, src/types/styles.ts
https://jam.dev/c/b3d952c1-1da8-4cc3-acf2-8b7dd8be8fca
=> feat: customize checkout UI with different flags

src/headlessMoneyHash.ts, src/types/intent.ts
Checkout PR for get installment plans - https://github.com/MoneyHash/one/pull/5496
=> feat: instalment plan state and method

package.json, src/headlessMoneyHash.ts, src/types/standaloneFields.ts
https://jam.dev/c/d1a6d2f3-b948-454c-929f-4175cab46efd
=> fix(cardelements): remove event listeners on elements validity event

package.json, src/headlessMoneyHash.ts, src/types/headless.ts
checkout PR - https://github.com/MoneyHash/one/pull/6677
=> feat: add bin lookup with receipt api

.eslintrc.json, package.json, src/headlessMoneyHash.ts
https://jam.dev/c/c37c2ce3-33c3-415a-bbe0-8f2985019515
=> feat: bin lookup without full pan number

package.json, src/headlessMoneyHash.ts, src/types/standaloneFields.ts
https://jam.dev/c/92551f48-c48b-4bd2-b1e9-048f2b031663
=> feat: enable basic luhn card validation by default
